# Generated by Django 2.1.1 on 2019-02-10 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostTitle', models.TextField()),
                ('PostDesc', models.TextField()),
                ('PostDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('Tags', models.TextField()),
                ('PostCategory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webSite.Category')),
            ],
        ),
    ]
