# Generated by Django 2.1.1 on 2019-02-10 14:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuthorName', models.TextField()),
                ('Title', models.TextField()),
                ('Description', models.TextField()),
                ('SendDate', models.DateTimeField(verbose_name=datetime.datetime(2019, 2, 10, 14, 22, 36, 799303, tzinfo=utc))),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webSite.Post')),
            ],
        ),
    ]
