# Generated by Django 2.1.1 on 2019-04-07 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='SendDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
